// Deterministic allocator for the 82 instant-winning codes.
// Re-run with the same SEED to reproduce the exact same allocation.
// Output: supabase/migrations/20260428100000_lottery_prizes.sql
//         scripts/lottery-prize-allocations.md

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');

const SEED = 20260428;

const TIERS = [
  { amount: 50,   count: 30 },
  { amount: 100,  count: 20 },
  { amount: 200,  count: 15 },
  { amount: 500,  count: 10 },
  { amount: 1000, count: 7  },
];

function mulberry32(seed) {
  return function () {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function shuffle(arr, rng) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

const codes = JSON.parse(readFileSync(resolve(repoRoot, 'scripts/lottery-codes.json'), 'utf8'));
if (codes.length !== 1002) {
  throw new Error(`Expected 1002 codes, found ${codes.length}`);
}
if (new Set(codes).size !== codes.length) {
  throw new Error('Duplicate codes detected in lottery-codes.json');
}

const totalWinners = TIERS.reduce((s, t) => s + t.count, 0);
if (totalWinners !== 82) {
  throw new Error(`TIERS must total 82 winners, got ${totalWinners}`);
}

const rng = mulberry32(SEED);
const shuffled = shuffle(codes, rng);

const allocations = {};
let cursor = 0;
for (const { amount, count } of TIERS) {
  allocations[amount] = shuffled.slice(cursor, cursor + count);
  cursor += count;
}

const allWinningCodes = Object.values(allocations).flat();
if (new Set(allWinningCodes).size !== 82) {
  throw new Error('Duplicate winners detected — bug in allocator');
}

const today = new Date().toISOString();

const migrationLines = [
  '-- ============================================================',
  '-- Lottery prize allocation (instant-winning codes)',
  `-- Generated by scripts/allocate-prizes.mjs (seed=${SEED}) at ${today}`,
  '-- 82 winning codes total: 30×50₪, 20×100₪, 15×200₪, 10×500₪, 7×1000₪',
  '-- ============================================================',
  '',
  '-- 1. Add prize_amount column (NULL = non-winner)',
  'ALTER TABLE lottery_codes ADD COLUMN IF NOT EXISTS prize_amount integer;',
  '',
  'CREATE INDEX IF NOT EXISTS idx_lottery_codes_prize',
  '  ON lottery_codes (prize_amount) WHERE prize_amount IS NOT NULL;',
  '',
  '-- 2. Assign prize amounts to the 82 winning codes',
];
for (const { amount } of TIERS) {
  const list = allocations[amount].map((c) => `'${c}'`).join(', ');
  migrationLines.push('');
  migrationLines.push(`-- ${allocations[amount].length} codes × ${amount}₪`);
  migrationLines.push(`UPDATE lottery_codes SET prize_amount = ${amount} WHERE code IN (${list});`);
}

migrationLines.push(
  '',
  '-- 3. Update the redemption function to return prize_amount on success',
  'DROP FUNCTION IF EXISTS redeem_lottery_code(text, text, text, text, text);',
  '',
  'CREATE OR REPLACE FUNCTION redeem_lottery_code(',
  '  p_code       text,',
  '  p_first_name text,',
  '  p_last_name  text,',
  '  p_phone      text,',
  '  p_venue      text',
  ')',
  'RETURNS jsonb',
  'LANGUAGE plpgsql',
  'SECURITY DEFINER',
  'SET search_path = public',
  'AS $$',
  'DECLARE',
  '  v_code_row    lottery_codes%ROWTYPE;',
  '  v_entry_id    uuid;',
  '  v_clean_code  text;',
  '  v_clean_phone text;',
  '  v_clean_venue text;',
  'BEGIN',
  '  v_clean_code  := upper(trim(p_code));',
  '  v_clean_phone := trim(p_phone);',
  '  v_clean_venue := trim(p_venue);',
  '',
  '  IF length(v_clean_code) != 6 THEN',
  "    RETURN jsonb_build_object('success', false, 'error', 'INVALID_CODE_FORMAT');",
  '  END IF;',
  '',
  "  IF trim(p_first_name) = '' OR trim(p_last_name) = '' OR v_clean_phone = '' OR v_clean_venue = '' THEN",
  "    RETURN jsonb_build_object('success', false, 'error', 'MISSING_FIELDS');",
  '  END IF;',
  '',
  "  IF (SELECT count(*) FROM lottery_entries WHERE submitted_at > now() - interval '1 minute') >= 10 THEN",
  "    RETURN jsonb_build_object('success', false, 'error', 'RATE_LIMITED');",
  '  END IF;',
  '',
  '  SELECT * INTO v_code_row',
  '  FROM lottery_codes',
  '  WHERE code = v_clean_code',
  '  FOR UPDATE;',
  '',
  '  IF NOT FOUND THEN',
  "    RETURN jsonb_build_object('success', false, 'error', 'CODE_NOT_FOUND');",
  '  END IF;',
  '',
  '  IF v_code_row.is_used THEN',
  "    RETURN jsonb_build_object('success', false, 'error', 'CODE_ALREADY_USED');",
  '  END IF;',
  '',
  '  IF EXISTS (SELECT 1 FROM lottery_entries WHERE phone = v_clean_phone) THEN',
  "    RETURN jsonb_build_object('success', false, 'error', 'DUPLICATE_PHONE');",
  '  END IF;',
  '',
  '  UPDATE lottery_codes',
  '  SET is_used = true, used_at = now()',
  '  WHERE id = v_code_row.id;',
  '',
  '  INSERT INTO lottery_entries (code_id, first_name, last_name, phone, venue)',
  '  VALUES (v_code_row.id, trim(p_first_name), trim(p_last_name), v_clean_phone, v_clean_venue)',
  '  RETURNING id INTO v_entry_id;',
  '',
  '  RETURN jsonb_build_object(',
  "    'success', true,",
  "    'entry_id', v_entry_id,",
  "    'prize_amount', v_code_row.prize_amount",
  '  );',
  'END;',
  '$$;',
  '',
  'GRANT EXECUTE ON FUNCTION redeem_lottery_code(text, text, text, text, text) TO anon;',
  'GRANT EXECUTE ON FUNCTION redeem_lottery_code(text, text, text, text, text) TO authenticated;',
);

writeFileSync(
  resolve(repoRoot, 'supabase/migrations/20260428100000_lottery_prizes.sql'),
  migrationLines.join('\n') + '\n',
);

const mdLines = [
  '# Lottery prize allocation',
  '',
  `**Seed:** \`${SEED}\``,
  `**Generated:** ${today}`,
  `**Total winning codes:** 82 / 1002`,
  '',
];
for (const { amount } of TIERS) {
  mdLines.push(`## ${amount}₪ — ${allocations[amount].length} codes`);
  mdLines.push('');
  mdLines.push(allocations[amount].join(', '));
  mdLines.push('');
}
writeFileSync(resolve(repoRoot, 'scripts/lottery-prize-allocations.md'), mdLines.join('\n') + '\n');

console.log(`Wrote supabase/migrations/20260428100000_lottery_prizes.sql`);
console.log(`Wrote scripts/lottery-prize-allocations.md`);
console.log('');
console.log(`Allocation summary (seed=${SEED}):`);
for (const { amount } of TIERS) {
  console.log(`  ${amount}₪: ${allocations[amount].length} codes`);
}
console.log(`  Total: ${allWinningCodes.length} winning codes / ${codes.length} total`);
console.log('');
console.log('Per-tier code lists:');
for (const { amount } of TIERS) {
  console.log('');
  console.log(`-- ${amount}₪ --`);
  console.log(allocations[amount].join(', '));
}
