-- ============================================================
-- A/B testing coupon codes (pre-launch QA)
-- Generated by scripts/generate-test-codes.mjs (seed=20260429) at 2026-04-28T07:45:08.021Z
-- 10 test codes that override the main lottery logic for QA
-- ============================================================

CREATE TABLE IF NOT EXISTS lottery_test_codes (
  code         text PRIMARY KEY,
  prize_amount integer,
  is_active    boolean NOT NULL DEFAULT true,
  notes        text,
  created_at   timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE lottery_test_codes ENABLE ROW LEVEL SECURITY;
-- No policies = deny all direct access; only the SECURITY DEFINER RPC can read this.

-- Seed the 10 test codes (idempotent — re-running keeps existing rows fresh)
INSERT INTO lottery_test_codes (code, prize_amount, notes) VALUES
  ('7FLWB6', 50, '#1 — Fixed 50₪ winner'),
  ('NDJ3W3', 100, '#2 — Fixed 100₪ winner'),
  ('2CGD4D', 200, '#3 — Fixed 200₪ winner'),
  ('A333XA', 500, '#4 — Fixed 500₪ winner'),
  ('83MJZW', 1000, '#5 — Fixed 1000₪ winner'),
  ('NL3JF9', NULL, '#6 — Fixed non-winner'),
  ('4EWM7H', 100, '#7 — Random predetermined 100₪'),
  ('V7L5K4', 200, '#8 — Random predetermined 200₪'),
  ('HSJ8QL', NULL, '#9 — Random predetermined non-winner'),
  ('H95EYA', NULL, '#10 — Random predetermined non-winner')
ON CONFLICT (code) DO UPDATE SET
  prize_amount = EXCLUDED.prize_amount,
  notes        = EXCLUDED.notes,
  is_active    = true;

-- Replace the redemption RPC: test codes are checked BEFORE production codes
DROP FUNCTION IF EXISTS redeem_lottery_code(text, text, text, text, text);

CREATE OR REPLACE FUNCTION redeem_lottery_code(
  p_code       text,
  p_first_name text,
  p_last_name  text,
  p_phone      text,
  p_venue      text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_code_row    lottery_codes%ROWTYPE;
  v_test_row    lottery_test_codes%ROWTYPE;
  v_entry_id    uuid;
  v_clean_code  text;
  v_clean_phone text;
  v_clean_venue text;
BEGIN
  v_clean_code  := upper(trim(p_code));
  v_clean_phone := trim(p_phone);
  v_clean_venue := trim(p_venue);

  -- TEST CODE OVERRIDE: bypass all production checks for QA
  SELECT * INTO v_test_row
  FROM lottery_test_codes
  WHERE code = v_clean_code AND is_active = true;

  IF FOUND THEN
    RETURN jsonb_build_object(
      'success', true,
      'entry_id', NULL,
      'prize_amount', v_test_row.prize_amount,
      'is_test', true
    );
  END IF;

  -- Production logic (unchanged from prior migration)
  IF length(v_clean_code) != 6 THEN
    RETURN jsonb_build_object('success', false, 'error', 'INVALID_CODE_FORMAT');
  END IF;

  IF trim(p_first_name) = '' OR trim(p_last_name) = '' OR v_clean_phone = '' OR v_clean_venue = '' THEN
    RETURN jsonb_build_object('success', false, 'error', 'MISSING_FIELDS');
  END IF;

  IF (SELECT count(*) FROM lottery_entries WHERE submitted_at > now() - interval '1 minute') >= 10 THEN
    RETURN jsonb_build_object('success', false, 'error', 'RATE_LIMITED');
  END IF;

  SELECT * INTO v_code_row
  FROM lottery_codes
  WHERE code = v_clean_code
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'CODE_NOT_FOUND');
  END IF;

  IF v_code_row.is_used THEN
    RETURN jsonb_build_object('success', false, 'error', 'CODE_ALREADY_USED');
  END IF;

  IF EXISTS (SELECT 1 FROM lottery_entries WHERE phone = v_clean_phone) THEN
    RETURN jsonb_build_object('success', false, 'error', 'DUPLICATE_PHONE');
  END IF;

  UPDATE lottery_codes
  SET is_used = true, used_at = now()
  WHERE id = v_code_row.id;

  INSERT INTO lottery_entries (code_id, first_name, last_name, phone, venue)
  VALUES (v_code_row.id, trim(p_first_name), trim(p_last_name), v_clean_phone, v_clean_venue)
  RETURNING id INTO v_entry_id;

  RETURN jsonb_build_object(
    'success', true,
    'entry_id', v_entry_id,
    'prize_amount', v_code_row.prize_amount
  );
END;
$$;

GRANT EXECUTE ON FUNCTION redeem_lottery_code(text, text, text, text, text) TO anon;
GRANT EXECUTE ON FUNCTION redeem_lottery_code(text, text, text, text, text) TO authenticated;
