-- ============================================================
-- Lottery prize allocation (instant-winning codes)
-- Generated by scripts/allocate-prizes.mjs (seed=20260428) at 2026-04-28T07:34:28.170Z
-- 82 winning codes total: 30×50₪, 20×100₪, 15×200₪, 10×500₪, 7×1000₪
-- ============================================================

-- 1. Add prize_amount column (NULL = non-winner)
ALTER TABLE lottery_codes ADD COLUMN IF NOT EXISTS prize_amount integer;

CREATE INDEX IF NOT EXISTS idx_lottery_codes_prize
  ON lottery_codes (prize_amount) WHERE prize_amount IS NOT NULL;

-- 2. Assign prize amounts to the 82 winning codes

-- 30 codes × 50₪
UPDATE lottery_codes SET prize_amount = 50 WHERE code IN ('3NJUXQ', 'FMXVV4', '55A2NJ', 'AUX8HH', 'WDVWPF', 'M4MJ77', '7CXNTD', 'ZVBN9S', 'Y8GCY5', 'EPT3E3', '3FGFGT', 'U6MF9H', '9NYFB6', 'YRTD6X', 'DB7CB4', 'YE2XJT', 'WEA84X', '7FZ9RR', 'G5VT4R', 'ZNBFFZ', 'B9CF86', 'VMDJSY', 'C2YXDU', 'QMEEJM', '34JUQW', '275XBP', 'VJUTPH', 'NS3ZMA', 'NVJDTW', 'BDDUKP');

-- 20 codes × 100₪
UPDATE lottery_codes SET prize_amount = 100 WHERE code IN ('Q4VFYK', '96RQG8', 'KH82C2', 'Z6B44J', 'TH4KRX', 'ZS39ZZ', 'K6SRKY', 'RZEFG5', 'NUJUA9', 'QUXWYU', 'TD49SA', 'UDM8G5', 'Z6XQ5J', 'BKJHM3', 'FPQ6Z3', '6TVM8C', 'TX8N5W', 'RH8NHS', 'Z8P6YV', 'GS3KYZ');

-- 15 codes × 200₪
UPDATE lottery_codes SET prize_amount = 200 WHERE code IN ('76JCZR', 'T8FQYD', 'TW9PQJ', 'EB8J4Z', 'AMXANC', 'XJEJWZ', '3JCU7A', 'Z83MUK', 'YHNUE3', '5YCWVV', 'NTHNMV', 'HC528Z', 'SQCGAK', '9BZMDP', 'YN9AB4');

-- 10 codes × 500₪
UPDATE lottery_codes SET prize_amount = 500 WHERE code IN ('WJFYT7', 'AS6CGK', '5D6YMD', 'MC6FXU', 'JZDSHW', 'TDVXRB', 'HMR6SX', 'XV5J67', 'QJ3N9F', 'RFRBKJ');

-- 7 codes × 1000₪
UPDATE lottery_codes SET prize_amount = 1000 WHERE code IN ('8KCD6G', 'UCNH8R', '2Z3D4Z', '3DGUTJ', 'MASPF9', 'HZQYE5', '6RTJ87');

-- 3. Update the redemption function to return prize_amount on success
DROP FUNCTION IF EXISTS redeem_lottery_code(text, text, text, text, text);

CREATE OR REPLACE FUNCTION redeem_lottery_code(
  p_code       text,
  p_first_name text,
  p_last_name  text,
  p_phone      text,
  p_venue      text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_code_row    lottery_codes%ROWTYPE;
  v_entry_id    uuid;
  v_clean_code  text;
  v_clean_phone text;
  v_clean_venue text;
BEGIN
  v_clean_code  := upper(trim(p_code));
  v_clean_phone := trim(p_phone);
  v_clean_venue := trim(p_venue);

  IF length(v_clean_code) != 6 THEN
    RETURN jsonb_build_object('success', false, 'error', 'INVALID_CODE_FORMAT');
  END IF;

  IF trim(p_first_name) = '' OR trim(p_last_name) = '' OR v_clean_phone = '' OR v_clean_venue = '' THEN
    RETURN jsonb_build_object('success', false, 'error', 'MISSING_FIELDS');
  END IF;

  IF (SELECT count(*) FROM lottery_entries WHERE submitted_at > now() - interval '1 minute') >= 10 THEN
    RETURN jsonb_build_object('success', false, 'error', 'RATE_LIMITED');
  END IF;

  SELECT * INTO v_code_row
  FROM lottery_codes
  WHERE code = v_clean_code
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'CODE_NOT_FOUND');
  END IF;

  IF v_code_row.is_used THEN
    RETURN jsonb_build_object('success', false, 'error', 'CODE_ALREADY_USED');
  END IF;

  IF EXISTS (SELECT 1 FROM lottery_entries WHERE phone = v_clean_phone) THEN
    RETURN jsonb_build_object('success', false, 'error', 'DUPLICATE_PHONE');
  END IF;

  UPDATE lottery_codes
  SET is_used = true, used_at = now()
  WHERE id = v_code_row.id;

  INSERT INTO lottery_entries (code_id, first_name, last_name, phone, venue)
  VALUES (v_code_row.id, trim(p_first_name), trim(p_last_name), v_clean_phone, v_clean_venue)
  RETURNING id INTO v_entry_id;

  RETURN jsonb_build_object(
    'success', true,
    'entry_id', v_entry_id,
    'prize_amount', v_code_row.prize_amount
  );
END;
$$;

GRANT EXECUTE ON FUNCTION redeem_lottery_code(text, text, text, text, text) TO anon;
GRANT EXECUTE ON FUNCTION redeem_lottery_code(text, text, text, text, text) TO authenticated;
